name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Replace with the branch name you're using for your Jekyll site

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and deploy Jekyll site
        uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
